/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/************Registers Address*************/
//RCC
#define RCC_BASE         0x40021000
#define RCC_APB2ENR      *(volatile int *)(RCC_BASE+0x18)
#define RCC_IOAEN        (1<<2)
#define RCC_IOBEN        (1<<3)

//GPIOA
#define GPIOA_BASE         0x40010800
#define GPIOA_CRH         *(volatile int *)(GPIOA_BASE+0x04)
#define GPIOA_CRL         *(volatile int *)(GPIOA_BASE+0x00)
#define GPIOA_ODR         *(volatile int *)(GPIOA_BASE+0x0C)
#define GPIOA_IDR         *(volatile int *)(GPIOA_BASE+0x08)

//GPIOB
#define GPIOB_BASE         0x40010C00
#define GPIOB_CRH         *(volatile int *)(GPIOB_BASE+0x04)
#define GPIOB_CRL         *(volatile int *)(GPIOB_BASE+0x00)
#define GPIOB_ODR         *(volatile int *)(GPIOB_BASE+0x0C)
#define GPIOB_IDR         *(volatile int *)(GPIOB_BASE+0x08)

void clock_init()
{
	//Enable GPIOA clock
	RCC_APB2ENR |= RCC_IOAEN;
	//Enable GPIOB clock
	RCC_APB2ENR |= RCC_IOBEN;
}

void GPIO_init()
{
	//reset registers .
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;

	//set pin A1 & A13 floating input ..CNF 01: Floating input (reset state)
	GPIOA_CRL |= (1<<6);
	//set pin A13 floating input ..CNF 01: Floating input (reset state)
	GPIOA_CRH |= (1<<22);

	//set pin B1  (push-pull) output...... MODE 01: Output mode, max speed 10 MHz.
	GPIOB_CRL |= (1<<4);
	//set pin B1  (push-pull) output...... MODE 01: Output mode, max speed 10 MHz.
	GPIOB_CRH |= (1<<20);
}

void wait_ms(int x){
	int i,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		//PB PUR by default 1 if press it will be 0....(single press)
		if(((GPIOA_IDR & (1<<1)) >> 1) == 0 )
		{
			GPIOB_ODR ^= (1<<1);
			while(((GPIOA_IDR & (1<<1)) >>1) == 0);//while pressing..single press.
		}
		//PB PDR by default 0 if press it will be 1....(multi pressing)
		if(((GPIOA_IDR & (1<<13)) >> 13) == 1 )
		{
			GPIOB_ODR ^= (1<<13);
		}
		wait_ms(1);
	}
}


