/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************/
#include"stm32f103c6_gpio_driver.h"

void clock_init()
{
	//Enable GPIOA clock
	GPIOA_CLK_EN();
	//Enable GPIOB clock
	GPIOB_CLK_EN();
}

void GPIO_init()
{
	Pin_config_t pin_cfg;
	//set pin A1 floating input ..CNF 01: Floating input (reset state)
	pin_cfg.GPIO_PinNumber = GPIO_PIN1;
	pin_cfg.GPIO_MODE = GPIO_MODE_INPUT_FLOAT;
	MCAL_GPIO_INIT(GPIOA,&pin_cfg);

	//set pin A13 floating input ..CNF 01: Floating input (reset state)
	pin_cfg.GPIO_PinNumber = GPIO_PIN13;
	pin_cfg.GPIO_MODE = GPIO_MODE_INPUT_FLOAT;
	MCAL_GPIO_INIT(GPIOA,&pin_cfg);

	//set pin B1  (push-pull) output...... MODE 01: Output mode, max speed 10 MHz.
	pin_cfg.GPIO_PinNumber = GPIO_PIN1;
	pin_cfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pin_cfg.GPIO_OUTPUT_speed = GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB,&pin_cfg);

	//set pin B13  (push-pull) output...... MODE 01: Output mode, max speed 10 MHz.
	pin_cfg.GPIO_PinNumber = GPIO_PIN13;
	pin_cfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pin_cfg.GPIO_OUTPUT_speed = GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB,&pin_cfg);
}

void wait_ms(int x){
	int i,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		//PB PUR by default 1 if press it will be 0....(single press)
		if((MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN1)) == 0 )
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN1);
			while((MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN1)) == 0 );//while pressing..single press.
		}
		//PB PDR by default 0 if press it will be 1....(multi pressing)
		if((MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN13)) == 1 )
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN13);
		}
		wait_ms(1);
	}
}


