/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "platform_types.h"
/************Rigesters Address*************/
//RCC
#define RCC_BASE         0x40021000
#define RCC_APB2ENR      *(volatile int *)(RCC_BASE+0x18)
#define RCC_IOAEN        (1<<2)
#define RCC_AFIOAEN      (1<<0)

//GPIO
#define GPIO_BASE         0x40010800
#define GPIO_CRH         *(volatile int *)(GPIO_BASE+0x04)
#define GPIO_CRL         *(volatile int *)(GPIO_BASE+0x00)
#define GPIO_ODR         *(volatile int *)(GPIO_BASE+0x0C)
#define GPIOA13          (1UL<<13)

//EXTI
#define EXTI_BASE         0x40010400
#define EXTI_IMR         *(volatile int *)(EXTI_BASE+0x00)
#define EXTI_RTSR        *(volatile int *)(EXTI_BASE+0x08)
#define EXTI_PR          *(volatile int *)(EXTI_BASE+0x14)

//AFIO
#define AFIO_BASE         0x40010000
#define AFIO_EXTICR1     *(volatile int *)(AFIO_BASE+0x08)

//NVIC
#define NVIC_BASE        0xE000E100
#define NVIC_EXTIE0     *(volatile int *)(NVIC_BASE+0x00)

void clock_init()
{
	//Enable GPIO clock
	RCC_APB2ENR |= RCC_IOAEN;
	//Enable AFIO clock
	RCC_APB2ENR |= RCC_AFIOAEN;
}

void GPIO_init()
{
	//set pin 13 output
	GPIO_CRH &= 0xFF0FFFFF;
	GPIO_CRH |= 0x00200000;
	//set pin A0 floating input
	GPIO_CRL |= (1<<2);
}

int main(void)
{
	clock_init();
	GPIO_init();
	//EXTI 0 configuration (x=0) to portA
	AFIO_EXTICR1 = 0;
	//Interrupt request from Line 0 is masked
	EXTI_IMR |= (1<<0);
	//Enable rising edge trigger.
	EXTI_RTSR |= (1<<0);
	//Enable IRQ6 ---EXTI0 in NVIC
	NVIC_EXTIE0 |= (1<<6);
	/* Loop forever */
	while(1);
}

void EXTI0_IRQHandler()
{
	//IRQ EXTI0 is happened ------PORTA pin0 _|- rising edge
	//toggle led at pin 13
	GPIO_ODR ^= (1<<13);
	EXTI_PR |= (1<<0);
}
